root@kali:~# apt-get update && apt-get upgrade && apt-get dist-upgrade

root@kali:~# apt-get install linux-headers-$(uname -r)

root@kali:~# wget http://download.virtualbox.org/virtualbox/5.0.4/virtualbox-5.0_5.0.4-102546~Ubuntu~trusty_amd64.deb

root@kali:~# dpkg -i virtualbox-5.0_5.0.4-102546~Ubuntu~trusty_amd64.deb

#vagrant install
wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
dpkg -i vagrant_1.7.4_x86_64.deb
